# Generated by Django 5.2.1 on 2025-05-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu_name', models.CharField(help_text='Identifier for the menu this item belongs to', max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('named_url', models.CharField(blank=True, help_text='Named URL (takes precedence over URL if both are specified)', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['menu_name'], name='tree_menu_m_menu_na_036b21_idx')],
            },
        ),
    ]
